{
    "app": {
        "host": "127.0.0.1",
        "port": 3100,
        "https": false,
        "timezone": "Asia/Shanghai",
        "locale": "en_US",
        "name": "main",
        "limit": {
            "interval": 60000,
            "rate": 100
        },
        "websockets": true,
        "prefix": "api",
        "url": "http://127.0.0.1:3100"
    },
    "content": {
        "searchType": "against"
    },
    "smtp": {
        "host": "smtp.163.com",
        "user": "azurlane16@163.com",
        "password": "WGLFANGCPNEBDLMZ",
        "secure": false,
        "from": "azurlane16@163.com",
        "resource": "/apps/turbo-fullstack-monorepo/apps/api/assets/emails",
        "port": 25
    }
}